In [4]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# Cities Breakdown

In [22]:
cities_18_dis =  pd.read_csv( r"C:/Users/zeusg/OneDrive/Documents/Github/data_vis/data/CDP/Cities/Cities Disclosing/2018_Cities_Disclosing_to_CDP.csv")

In [23]:
cities_18_dis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641 entries, 0 to 640
Data columns (total 13 columns):
Year Reported to CDP    641 non-null int64
Account Number          641 non-null int64
Organization            641 non-null object
City                    641 non-null object
Country                 641 non-null object
CDP Region              641 non-null object
Reporting Authority     641 non-null object
Access                  641 non-null object
First Time Discloser    641 non-null object
Population              586 non-null float64
Population Year         641 non-null int64
City Location           641 non-null object
Last update             641 non-null object
dtypes: float64(1), int64(3), object(9)
memory usage: 65.2+ KB

In [24]:
# Simplify removing duplicate columns
cities_18_dis = cities_18_dis[['Year Reported to CDP', 'Account Number', 'City', 'Country', 'CDP Region', 'Access', 'Population', 'Population Year', 'City Location']]
#Rename columns
cities_18_dis = cities_18_dis.rename(columns={'Year Reported to CDP': 'Year', 'Account Number': 'Account','CDP Region':'Region','City Location':'Location'})

In [25]:
cities_18_dis.head()

,Year,Account,City,Country,Region,Access,Population,Population Year,Location
0,2018,58671,Helsingør,Denmark,Europe,public,62686.0,2017,POINT (12.5921 56.0308)
1,2018,59167,Providencia,Chile,Latin America,public,126487.0,2012,POINT (-70.6092 -33.4313)
2,2018,50553,Fresno,United States of America,North America,public,527438.0,2017,POINT (-119.773 36.7468)
3,2018,826407,Mirandela,Portugal,Europe,public,11852.0,2011,POINT (-7.1753 41.51)
4,2018,60375,Archipiélago de San Andrés,Colombia,Latin America,public,120000.0,2017,POINT (-81.6976 12.5794)

## Cities Responses

In [40]:
cities_18_res =  pd.read_csv( r"C:/Users/zeusg/OneDrive/Documents/Github/data_vis/data/CDP/Cities/Cities Responses/2018_Full_Cities_Dataset.csv")

In [41]:
cities_18_res.head()

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
0,CDP Cities 2018,2018,3203,City of Chicago,United States of America,North America,Water,Wastewater,16.1,Please provide the percentage breakdown of the...,1,Percentage of wastewater collected,5,Other type of wastewater,NaN,NaN,NaN,24/06/2020 05:28:18 AM
1,CDP Cities 2018,2018,50555,City of Hamilton,Canada,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,5,Probability of hazard,4,NaN,Medium High,NaN,NaN,24/06/2020 05:28:18 AM
2,CDP Cities 2018,2018,50392,Prefeitura de Vitória,Brazil,Latin America,Emissions Reduction: City-wide,Emissions Reduction Actions : City-wide,8.4,What actions is your city taking to reduce emi...,1,Emissions reduction project activity,3,NaN,On-site renewable energy generation,NaN,NaN,24/06/2020 05:28:18 AM
3,CDP Cities 2018,2018,36522,Comune di Verbania,Italy,Europe,Strategy,Energy,9.0,Please indicate the energy mix of electricity ...,2,Gas,1,Energy consumption percentage,NaN,NaN,NaN,24/06/2020 05:28:18 AM
4,CDP Cities 2018,2018,35873,Municipality of Medellín,Colombia,Latin America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,3,Magnitude of impact,6,NaN,Serious,NaN,NaN,24/06/2020 05:28:18 AM

In [42]:
_ = cities_18_res.loc[cities_18_res['Organization'] == 'New York City']

In [44]:
_

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
480,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,10,Impact description,2,NaN,Nor'Easter can cause coastal flooding and pose...,NaN,NaN,24/06/2020 05:28:18 AM
529,CDP Cities 2018,2018,3417,New York City,United States of America,North America,City Wide Emissions,City-wide external verification,7.12b,Please explain why your city-wide emissions in...,2,Comments,1,Please explain,NaN,NaN,NaN,24/06/2020 05:28:18 AM
561,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Governance and Data Management,Governance,1.2,Please describe the administrative structure o...,2,Description of administrative structure,1,Government structure,"The City government, which is led by a Mayor a...",NaN,NaN,24/06/2020 05:28:18 AM
623,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Energy Data,Scope 1 Emissions Breakdown,6.5,Please give the total amount of fuel (refers t...,1,Source,13,NaN,Wastewater treatment,NaN,NaN,24/06/2020 05:28:18 AM
849,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Adaptation,Adaptation Actions,3.3,Please describe the actions you are taking to ...,3,Status of action,5,NaN,Implementation,NaN,NaN,24/06/2020 05:28:18 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185859,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Energy Data,Scope 1 Emissions Breakdown,6.5,Please give the total amount of fuel (refers t...,2,Fuel,22,NaN,Other : HFC,NaN,NaN,24/06/2020 05:28:18 AM
185897,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Emissions Reduction: Local Government,Emissions Reduction Actions: Local Government,8.1,What actions are you undertaking to reduce you...,1,Emissions reduction project activity,7,NaN,Water metering and billing,NaN,NaN,24/06/2020 05:28:18 AM
186265,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Water,Wastewater,16.1,Please provide the percentage breakdown of the...,2,No treatment,1,Black water/sewage,NaN,NaN,NaN,24/06/2020 05:28:18 AM
186631,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Emissions Reduction: City-wide,Emissions Reduction Actions : City-wide,8.4,What actions is your city taking to reduce emi...,6,Web link to project website,23,NaN,NaN,NaN,NaN,24/06/2020 05:28:18 AM
186659,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Hazards and Adaptation,Adaptation,3.4,Please describe the main goals of your city’s ...,4,Source of goal,8,NaN,Local government,NaN,NaN,24/06/2020 05:28:18 AM